/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoPatientRouteImport } from './routes/demo.patient'
import { Route as DemoCaregiverRouteImport } from './routes/demo.caregiver'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated/summary'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPhotosRouteImport } from './routes/_authenticated/photos'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedCuesRouteImport } from './routes/_authenticated/cues'
import { Route as AuthenticatedCircleRouteImport } from './routes/_authenticated/circle'
import { Route as DemoCaregiverLogsRouteImport } from './routes/demo.caregiver.logs'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPatientRoute = DemoPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCaregiverRoute = DemoCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => DemoRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhotosRoute = AuthenticatedPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuesRoute = AuthenticatedCuesRouteImport.update({
  id: '/cues',
  path: '/cues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCircleRoute = AuthenticatedCircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoCaregiverLogsRoute = DemoCaregiverLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DemoCaregiverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/patient': typeof PatientRoute
  '/circle': typeof AuthenticatedCircleRoute
  '/cues': typeof AuthenticatedCuesRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/today': typeof AuthenticatedTodayRoute
  '/demo/caregiver': typeof DemoCaregiverRouteWithChildren
  '/demo/patient': typeof DemoPatientRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/caregiver/logs': typeof DemoCaregiverLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/patient': typeof PatientRoute
  '/circle': typeof AuthenticatedCircleRoute
  '/cues': typeof AuthenticatedCuesRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/today': typeof AuthenticatedTodayRoute
  '/demo/caregiver': typeof DemoCaregiverRouteWithChildren
  '/demo/patient': typeof DemoPatientRoute
  '/demo': typeof DemoIndexRoute
  '/demo/caregiver/logs': typeof DemoCaregiverLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/patient': typeof PatientRoute
  '/_authenticated/circle': typeof AuthenticatedCircleRoute
  '/_authenticated/cues': typeof AuthenticatedCuesRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/photos': typeof AuthenticatedPhotosRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/demo/caregiver': typeof DemoCaregiverRouteWithChildren
  '/demo/patient': typeof DemoPatientRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/caregiver/logs': typeof DemoCaregiverLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/demo'
    | '/patient'
    | '/circle'
    | '/cues'
    | '/learn'
    | '/onboarding'
    | '/photos'
    | '/profile'
    | '/settings'
    | '/summary'
    | '/today'
    | '/demo/caregiver'
    | '/demo/patient'
    | '/demo/'
    | '/demo/caregiver/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/patient'
    | '/circle'
    | '/cues'
    | '/learn'
    | '/onboarding'
    | '/photos'
    | '/profile'
    | '/settings'
    | '/summary'
    | '/today'
    | '/demo/caregiver'
    | '/demo/patient'
    | '/demo'
    | '/demo/caregiver/logs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/demo'
    | '/patient'
    | '/_authenticated/circle'
    | '/_authenticated/cues'
    | '/_authenticated/learn'
    | '/_authenticated/onboarding'
    | '/_authenticated/photos'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/summary'
    | '/_authenticated/today'
    | '/demo/caregiver'
    | '/demo/patient'
    | '/demo/'
    | '/demo/caregiver/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRouteWithChildren
  PatientRoute: typeof PatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/patient': {
      id: '/demo/patient'
      path: '/patient'
      fullPath: '/demo/patient'
      preLoaderRoute: typeof DemoPatientRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/caregiver': {
      id: '/demo/caregiver'
      path: '/caregiver'
      fullPath: '/demo/caregiver'
      preLoaderRoute: typeof DemoCaregiverRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/photos': {
      id: '/_authenticated/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AuthenticatedPhotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cues': {
      id: '/_authenticated/cues'
      path: '/cues'
      fullPath: '/cues'
      preLoaderRoute: typeof AuthenticatedCuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circle': {
      id: '/_authenticated/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof AuthenticatedCircleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/caregiver/logs': {
      id: '/demo/caregiver/logs'
      path: '/logs'
      fullPath: '/demo/caregiver/logs'
      preLoaderRoute: typeof DemoCaregiverLogsRouteImport
      parentRoute: typeof DemoCaregiverRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCircleRoute: typeof AuthenticatedCircleRoute
  AuthenticatedCuesRoute: typeof AuthenticatedCuesRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPhotosRoute: typeof AuthenticatedPhotosRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCircleRoute: AuthenticatedCircleRoute,
  AuthenticatedCuesRoute: AuthenticatedCuesRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPhotosRoute: AuthenticatedPhotosRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoCaregiverRouteChildren {
  DemoCaregiverLogsRoute: typeof DemoCaregiverLogsRoute
}

const DemoCaregiverRouteChildren: DemoCaregiverRouteChildren = {
  DemoCaregiverLogsRoute: DemoCaregiverLogsRoute,
}

const DemoCaregiverRouteWithChildren = DemoCaregiverRoute._addFileChildren(
  DemoCaregiverRouteChildren,
)

interface DemoRouteChildren {
  DemoCaregiverRoute: typeof DemoCaregiverRouteWithChildren
  DemoPatientRoute: typeof DemoPatientRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoCaregiverRoute: DemoCaregiverRouteWithChildren,
  DemoPatientRoute: DemoPatientRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRouteWithChildren,
  PatientRoute: PatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
